name: wordgame
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  animated_toggle_switch: ^0.8.5
  image_picker: ^1.2.0
  audioplayers: ^6.5.1
  provider: ^6.1.5+1
  vibration: ^3.1.4
  get: ^4.7.2
  flutter_animate: ^4.5.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/voice/
    - assets/images/
    - assets/images/hangman/
